version: "3.9"

services:
  comfyui:
    image: ghcr.io/tuxstack/comfyui_custom:latest
    ports:
      - "8188:8188"
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    volumes:
      - comfyui_models:/root/comfyui/models
      - comfyui_outputs:/root/comfyui/outputs
      - comfyui_input:/root/comfyui/input
      - comfyui_custom_nodes:/root/comfyui/custom_nodes
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.gpu == true
          - node.labels.comfyui == true
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

volumes:
  comfyui_models:
  comfyui_outputs:
  comfyui_input:
  comfyui_custom_nodes:
