version: "3.9"

services:
  comfyui:
    image: ghcr.io/<you>/<comfyui-image>:latest   # or public image -> no registry auth needed
    container_name: comfyui
    ports:
      - "8188:8188"
    environment:
      # enable GPU if you have one; remove if CPU-only
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    volumes:
      - ./models:/root/comfyui/models
      - ./outputs:/root/comfyui/outputs
      - ./input:/root/comfyui/input
      - ./custom_nodes:/root/comfyui/custom_nodes
    restart: unless-stopped
    # swarm-friendly (ignored by docker compose)
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
