version: "3.9"

services:
  comfyui:
    image: ghcr.io/<you>/<comfyui-image>:latest   # or your registry/image:tag
    ports:
      - "8188:8188"
    environment:
      # NVIDIA envs are harmless if the node has no GPU, but we also constrain placement
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      COMFYUI_HOST: "0.0.0.0"
      COMFYUI_PORT: "8188"
    volumes:
      # Use named volumes so the data stays on rea (local driver = local to that node)
      - comfyui_models:/root/comfyui/models
      - comfyui_outputs:/root/comfyui/outputs
      - comfyui_input:/root/comfyui/input
      - comfyui_custom_nodes:/root/comfyui/custom_nodes
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          # EITHER pin by label (recommended)...
          - node.labels.gpu == true
          - node.labels.comfyui == true
          # ...OR pin by hostname instead of labels:
          # - node.hostname == rea
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Swarm ignores 'container_name' and 'gpus:'; that's expected

volumes:
  comfyui_models:
  comfyui_outputs:
  comfyui_input:
  comfyui_custom_nodes:
